### PR TITLE
PostsPage & ProfilePage upgrade to use Hooks

### PR DESCRIPTION
**Pull request by ann0nip**
I did a refactor for those two components to use Hooks before starting with the Pagination task.

### CODE REVIEW

**Comment by itsnitinr** [comment]
Hi @ann0nip. Thanks for the PR but could you explain why you decided to make a separate posts reducer? Also, I feel that converting redux code to hooks in only some components would break the consistency of the app. But maybe I could refactor all of them one day.

**Comment by ann0nip** [comment]
Hello @itsnitinr,
I decided to create a posts reducers because it's caused confusion in post reducer due that post reducer is in charge of singles data, not a list of. Like posts (which now has all posts and user posts).

Regarding the hooks, fortunately, they are backward-compatible and eventually, you should refactor progressively your components. 

Anyway, if you're not comfortable it's okay.

**Comment by itsnitinr** [comment]
Great @ann0nip, thanks for explaining. I will test the commits in some time and merge them. Thanks for contributing.

**Comment by itsnitinr** [comment]
Hi @ann0nip. Sorry for the delay. Great job. One request: Can you add pagination to the `ProfilesPage.component.jsx` page as well? It's the longest page of the website (developers page). You have added pagination to `ProfilePosts.component.jsx`, much appreciated.

**Comment by ann0nip** [comment]
Hello, 

Yes, I can. Are you going to merge this first?

**Comment by itsnitinr** [comment]
I was planning to merge it once even this is done. You don't have to create new PRs for each commit btw. GitHub will automatically all your new commits to existing PRs.

**Comment by ann0nip** [comment]
Hey @itsnitinr, 
All right, hopefully on Sunday, I will work on that. 
About the PR I know, but in that way, it doesn't count for the Hacktoberfest event so, I need to create PR separately

**Comment by itsnitinr** [comment]
Okay @ann0nip. Take your time, no issues.

**Pull request merged**
